version: '3.8'

services:
  web:
    build:
      context: ./
    command: python ./blog/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/drf_blog_api/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:14.9-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    env_file:
      - ./.env.db
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume: